schema: 
  - https://graphql.contentful.com/content/v1/spaces/${CONTENTFUL_SPACE_ID}:
      headers:
        Authorization: "Bearer ${CONTENTFUL_ACCESS_TOKEN}"
documents:
  - '**/*.graphql'
  - '**/*.tsx'
plugins:
  - typescript-operations
  - typescript-react-apollo
cacheDir: .cache